[project]
name = "heroku"
version = "0.1.0"
description = "uv runable script to manage Heroku accounts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argcomplete>=3.5.1",
    "pyperclip>=1.9.0",
]
